# Пример файла secrets.yaml для ESPHome.
# Скопируйте в secrets.yaml (он не попадает в Git) и укажите реальные пароли:

wifi_ssid: "Roy"
wifi_password: "YOUR_WIFI_PASSWORD"
ota_password: "YOUR_OTA_PASSWORD"
api_encryption_key: "YOUR_NOISE_PSK_KEY"
